#!/bin/bash

create_missing_dirs() {
    while [[ $# -gt 0 ]]; do
        case "$1" in
            -v|--volume)
                IFS=':' read -ra VOLUME <<< "$2"
                host_path="${VOLUME[0]}"
                if [[ ! -e "$host_path" ]]; then
                    mkdir -p "$host_path"
                fi
                shift 2
                ;;
            *)
                shift
                ;;
        esac
    done
}

remove_network_option() {
    local args=()
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --network=*)
                shift
                ;;
            --network)
                if [[ "$2" != --* && -n "$2" ]]; then
                    shift
                fi
                shift
                ;;
            *)
                args+=("$1")
                shift
                ;;
        esac
    done
    echo "${args[@]}"
}

if [[ "$1" == "create" ]]; then
    shift
    create_missing_dirs "$@"
    
    # Remove existing --network option and store cleaned args
    cleaned_args=$(remove_network_option "$@")
    
    # Run podman with host network and cleaned args
    exec /usr/bin/podman create --network=slirp4netns ${cleaned_args}
else
    exec /usr/bin/podman "$@"
fi
